INCLUDE(FindPackageHandleStandardArgs)

FIND_PATH(GLEW_INCLUDE_PATH GL/glew.h)
FIND_LIBRARY(GLEW_LIBRARY_PATH GLEW)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(GLEW DEFAULT_MSG 
                                  GLEW_INCLUDE_PATH 
                                  GLEW_LIBRARY_PATH)

IF(GLEW_FOUND)
  SET(GLEW_INCLUDE_DIRS ${GLEW_INCLUDE_PATH})
  SET(GLEW_LIBRARIES ${GLEW_LIBRARY_PATH})
ENDIF(GLEW_FOUND)
